"""user_table

Revision ID: dfd61a14369b
Revises: 
Create Date: 2024-12-15 00:29:43.412702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from migration.TableInit import TableInit

# revision identifiers, used by Alembic.
revision: str = 'dfd61a14369b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TYPE user_role AS ENUM ('admin', 'user', 'seller');  
        """
    )
    op.execute(
        """
        CREATE TABLE users (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            username VARCHAR(255) NOT NULL UNIQUE,
            email VARCHAR(255) NOT NULL UNIQUE,
            first_name VARCHAR(255) NOT NULL,
            last_name VARCHAR(255) NOT NULL,
            hash_password VARCHAR(255) NOT NULL,
            role user_role DEFAULT 'user'
        );  
        """
    )
    users_columns_types = {
        'id' : int,
        'username' : str, 
        'first_name' : str,
        'last_name' : str,
        'email' : str,
        'hash_password' : str
    }
    users = TableInit.parse_data('./migration/versions/csv_data/users_clear.csv', users_columns_types, ignore_rows = [0])
    for user in users:
        op.execute(
            sa.text("INSERT INTO users (username, first_name, last_name, email, hash_password) VALUES (:username, :first_name, :last_name, :email, :hash_password)").params(user)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DROP TYPE user_role CASCADE;
        """
    )
    op.execute(
        """
        DROP TABLE users;
        """
    )
    pass
    # ### end Alembic commands ###
