"""genre_table

Revision ID: 736850cd3c1e
Revises: 5d8cb88bb054
Create Date: 2024-12-15 17:52:55.280299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from migration.TableInit import TableInit

# revision identifiers, used by Alembic.
revision: str = '736850cd3c1e'
down_revision: Union[str, None] = '5d8cb88bb054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE genres (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            title VARCHAR(255) NOT NULL UNIQUE
        );  
        """
    )
    genre_columns_types = {
        'id' : int,
        'title' : str
    }
    genres = TableInit.parse_data('./migration/versions/csv_data/genre.csv', genre_columns_types, ignore_rows = [0])
    for genre in genres:
        op.execute(
            sa.text("INSERT INTO genres (title) VALUES (:title)").params(genre)
        )


def downgrade() -> None:
    op.execute(
        """
        DROP TABLE genres;
        """
    )
