"""jwttoken_table

Revision ID: 91b8485375a3
Revises: dfd61a14369b
Create Date: 2024-12-15 02:05:09.134414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91b8485375a3'
down_revision: Union[str, None] = 'dfd61a14369b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     op.execute(
        """
        CREATE TABLE issued_jwt_tokens (
            jti UUID NOT NULL DEFAULT gen_random_uuid(),
            device_id UUID NOT NULL,
            user_id INTEGER NOT NULL,
            PRIMARY KEY (jti, user_id),
            FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
        );  
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DROP TABLE issued_jwt_tokens;
        """
    )
    pass
    # ### end Alembic commands ###
